name: flutter_sql_crud_by_inzimam
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sqflite: ^2.0.3+1
  path_provider: ^2.0.2
  intl: ^0.17.0
  open_mail_app: ^0.4.5
  photo_view: ^0.14.0
  url_launcher: ^6.1.5
  image_picker: any

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

